spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/formulario-cadastro-db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:canadalpk1}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
